# Generated by Django 2.2.7 on 2019-11-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='audience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
